name: student_info
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_secure_storage: ^8.0.0
  modal_progress_hud_nsn: ^0.3.0
  intl: ^0.18.0
  # shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

 
  assets:
    - images/
   

